<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <Version>1.1.0</Version>
    <Authors>FileRedact</Authors>
    <Product>FileRedact</Product>
  </PropertyGroup>
</Project>
